### ISSUE TITLE
Is this library being used in production?

### ISSUE THREAD

**Issue by maddie** [DrmagicE/gmqtt#17]
If yes, in what kind of environment, with what kind of workload?

I'm interested in embedded this into our project which will run in production with tens of thousands of devices connected in the coming future, so I'd like to have a rough estimation on what I can expect from gmqtt.

Thanks!

**Comment by DrmagicE** [comment]
It was. I am not sure whether it is still running in production, because I have left the company. Gmqtt worked fine with about hundreds of connections while each connection published QoS 1 message every 15 seconds. Because there were just a few connections, it takes only little resources under an 8-core 16G RAM machine.  Feel free to open issues if you have any problems during integration.

**Comment by maddie** [comment]
I see, thanks. This seems to be a great project, keep up the good work!

**Comment by DrmagicE** [comment]
It was. 
