### ISSUE TITLE
Unable to connect using websocket client by HiveMQ

### ISSUE THREAD

**Issue by KingRial** [DrmagicE/gmqtt#23]
I was testing the library using the [Websocket example](https://github.com/DrmagicE/gmqtt/tree/master/examples/wswss)  and I found out that I am unable to connect using the client offered by [HiveMQ](http://www.hivemq.com/demos/websocket-client/) with the following error:

**Connect failed: AMQJS0007E Socket error:undefined.**
**WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received**

![image](https://user-images.githubusercontent.com/886518/76079771-b0486b00-5fa5-11ea-9464-aa7db83705c1.png)

**Comment by DrmagicE** [comment]
You are trying to connect 127.0.0.1 of the HiveMQ server , not your host.

**Comment by KingRial** [comment]
I launched locally the MQTT broker ^^

Using plain MQTT clients all the stress tests were succesfull.
Using MQTTws clients,, the HiveMQ client failed to connect.

**Comment by DrmagicE** [comment]
I see. This is a bug. Thanks for your feedback.  I will fix it

**Comment by DrmagicE** [comment]
@KingRial  Hi,after doing some digging, i find that the hivemq client is sending invalid  Sec-WebSocket-Protocol header:
![image](https://user-images.githubusercontent.com/13395096/76094933-6a6bc100-5ffe-11ea-8fcd-ca612f864fba.png)

According to the spec: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html
![image](https://user-images.githubusercontent.com/13395096/76095125-b74f9780-5ffe-11ea-9bf1-8c2564479bce.png)
It should only be "mqtt", otherwise, the broker should reject the client, and gmqtt only support v3.1.1 for now,so v3.1 should not work.
