### ISSUE TITLE
crash on unaligned uint64 when using in arm

### ISSUE THREAD

**Issue by WK-LLP** [DrmagicE/gmqtt#28]
Hello, thank you for providing the way to implement mqtt server in go. Now I am testing it at the arm board. When the client connect, it cause the crash. I find that storing int64 using atomic mode at arm32 sometimes will cause "the crash on unaligned uint64". It's the code in the source below, in the file "src/runtime/internal/atomic/atomic_arm.go".

//go:nosplit
func goStore64(addr *uint64, v uint64) {
	if uintptr(unsafe.Pointer(addr))&7 != 0 {
		*(*int)(nil) = 0 // crash on unaligned uint64
	}
	_ = *addr // if nil, fault before taking the lock
	addrLock(addr).lock()
	*addr = v
	addrLock(addr).unlock()
}

Do you have some solution to solve it? Thank for very much !

**Comment by DrmagicE** [comment]
Sorry for the trouble, gmqtt has not been tested on arm and x86-32 platform. The panic is caused by unaligned uint64 in `client` struct https://github.com/DrmagicE/gmqtt/blob/v0.1.3/client.go#L96. 

[sync/atomic "BUG" note](https://golang.org/pkg/sync/atomic/#pkg-note-BUG):
> On ARM, x86-32, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.

Here is the solutions:
1.  use x86-64 instead of arm if possible.
2. make the client struct to be "64-bit aligned". (welcome PR)

**Comment by DrmagicE** [comment]
Hi. PR https://github.com/DrmagicE/gmqtt/pull/31 should solve your problem.
