### ISSUE TITLE
Improvement and Features roadmap

### ISSUE THREAD

**Issue by saeidakbari-ir** [DrmagicE/gmqtt#42]
Hi
I personally really appreciate this project and its potential to be a powerful MQTT message broker.

As the README mentioned currently there is not support for clustering and it's fine for a young project but I suggest maintainers of the project create a roadmap and guideline for further improvement and the ability to works in the cluster mode. e.g the way that clustering should be implemented and its architecture.

Also, a contribution guild would be very helpful for anyone how likes to contribute and improve this project As I personally love to do to get rid of the current chunky erlang broker cluster that we have.

**Comment by DrmagicE** [comment]
Thank you for the attention and recognition. 

For now, I am using a simple TODO list (which is at the bottom of the README) to manage the further feature and improvement. I think it still works fines for now because as you mentioned it is a young project but I will try the github milestones for better roadmap management. 

I am designing the cluster architecture recently and I would like to share my ideas on the issue tracker.

Contributions are always welcome, I will add some guidelines latter.

**Comment by DrmagicE** [comment]
Thanks again for the good advise. The contribution guide has been added via https://github.com/DrmagicE/gmqtt/pull/44.
Feel free to reopen or comment if you have any questions about Gmqtt or the guideliines :)
