### ISSUE TITLE
discussion: Cluster design

### ISSUE THREAD

**Issue by DrmagicE** [DrmagicE/gmqtt#43]
Due to the MQTT protocol architecture, it is difficult or may be impossible to meet all requirements in MQTT specification.
The key point of clustering MQTT brokers is the tradeoffs between consistency and availability.

# Basic Idea
The basic idea of gmqtt cluster is just like other popular brokers, emq,vernmq,HiveMQ, etc.
It is a masterless cluster, each nodes in cluster are equals. User can choose either server-side or client-side load balance to connect the cluster.  
![image](https://user-images.githubusercontent.com/13395096/103364661-5cd97780-4af9-11eb-80e2-f89f0bc4971b.png)

# Consistency & Availability
## Network Partition
When network partition happens, we have 2 options:
### 1. trade consistency for availability
All nodes will continue serving, any message, subscribe, unsubscribe, connect, disconnect event will be delivered once the network partition heals. It is an eventually consistent model. Of course, the message order can not be perserved in this situation.  
If the partition do not heal and reach a timeout or the event buffer is full, the cluster should remove the node automatic. It may cause message loss.
### 2. trade availability for consistency  
All nodes will return negative ack for subscribe, unsubscribe, connect packet. For publish packet：
• If the client protocol is V3, then closes the client because there is no negative ack for publish packet in V3 protocol.
• If the client protocol is V5, then returns a negative ack.

When the partition heals, all nodes can re-join to the cluster automaticly.  
If we trade availability for consistency, the cluster can not provide fault tolerance——any node goes down will cause the whole cluster become unavailable.
Gmqtt will make this tradeoff strategy configurable like how vernemq does. 
> reference: https://docs.vernemq.com/clustering/netsplits

## session state
In gmqtt cluster, the session state will not replicate to other nodes. Which means the client can not resume a session from different nodes. 
The reason is that it is very difficult and requires a lot of extra works to do to copy session state and maintain the consistency across nodes. This comment https://github.com/emqx/emqx/issues/1623#issuecomment-395326544 elaborates the difficulties. 
Due to this complexity, both EMQ and vernemq do not support session migration yet. 

# Inner-node Communication
TODO

Some reference:
* https://docs.vernemq.com/clustering/introduction
* https://docs.emqx.io/en/broker/latest/advanced/cluster.html

**Comment by saeidakbari-ir** [comment]
If I'm not wrong, gmqtt can store sessions and subscriptions in both Redis and memory. in the case of memory, the cluster must be able to sync all of the node states with each other for maintaining the cluster in the true state. but in another case, Redis can be used as a single source of truth (However Redis itself is can not be considered consistent in some situations).

in both, Redis and Memory cluster have to have a single leader hows responsible for managing the sessions and subscriptions. Also by now, the topic tree will be store in memory after a client subscribes even in the case of reading initially from Redis and it could cause challenges for syncing subscription state.

P.S: Correct me if I'm wrong.

**Comment by DrmagicE** [comment]
@saeidakbari-ir Thanks for sharing your ideas :) Yes, the session and subscriptions must be sync to all nodes in the cluster, but I would like to replica them rather than read them from a single source.

The persistence layer in gmqtt is not designed for sharing with other nodes, so any implementation should follow the same rule.  Although the redis can be used as a single source in the cluster, but I will suggest every node in the cluster should have their own persistence backend, which can improve both performance and availability. 

I suggests the MQTT cluster should be masterless which means there is no leader in the cluster, all node in the cluster are equal. The nodes should run behind a load balance which is also a normal architecture for most MQTT broker. For examples, every node in the cluster can be connected by a client, when a node receives a subscribe packet, it will replica the subscription to other nodes, and when it receives a publish message, it should only deliver the message to those nodes which has associated subscriptions.

And currently, I am trying to use the gossip protocol(masterless style) to manage the cluster membership instead of raft(leader-follower style), and I found this package should be helpful https://github.com/hashicorp/serf. 

I don’t have too much ideas for briding now, maybe we can discuss it latter.

**Comment by saeidakbari-ir** [comment]
@DrmagicE The idea for using gossip is kinda OK but not enough. gossip or any implementation of it likes the one you mentioned is only for node orchestration and management. despite the fact that they aren't made for consensus, I think we also need a consensus protocol like Raft or Paxos.
What we also need is a protocol for maintaining the decisions on some processes like subscription and session management the way that cluster stays in a consistent state.
I think the aggregation of gossip and Raft would be very helpful for peer-to-peer node discovery and also maintaining consensus.

About the idea that every node in the cluster should have its own persistence backend, I think it would be useful for the persistence layer which does not have the ability to cluster themselves like Redis because I think it became extra work to have a sidecar along with gmqtt that can be clustered itself. by the way, it's a very good idea for the memory persistence layer that is implemented in gmqtt itself.

I still looking to find information on briding messages and I will notify I if find any.

**Comment by DrmagicE** [comment]
@saeidakbari-ir Hi, I have updated the design. You can take a look and give me some feedback, thanks.

**Comment by azynet1** [comment]
你好，我做物联网设计的，大部分物联网应用设计对会话保持并不依赖，因为硬件设备在断电后，无法判断自身的 会话状态。不过保留消息应用比较多，集群是否可以支持保留消息不会单点故障。

**Comment by DrmagicE** [comment]
From google translate:

**Comment by DrmagicE** [comment]
@azynet1 要保证保留消息不丢有点难度。建议可以直接用插件把消息直接写到kafka队列.

**Comment by saeidakbari-ir** [comment]
@DrmagicE Hi
Thanks for sharing your design and idea. I looked into the design and there are some major concerns.
The fact that your design is a good start point and I also prefer availability over consistency but not at the level of sacrificing it. The gmqtt must allow users to configure consistency according to their needs.

As your design shows there is no share data except the topic tree allowing all nodes to know which client has subscribed to which node, all session data for each node store on that node but here where the problems start.

1. gossip protocol takes some time to inform all cluster nodes that the client subscribed so every publish message would deliver to the clients. There is precisely why I do not suggest use gossip for data (not membership and node informing) event handling because it could potentiality leads to fault result and data loss.
2. Admin API needs all states of the cluster for returning correct information of connected clients or for example disconnect a specific client from the cluster. with each information stored in each node, it could not be possible, the things that other MQTT brokers provide such as EMQX and VerneMQ.

We also need a streaming protocol like Redis stream or NATS steam for data passing among the nodes. I don't think direct requests such as gRPC or REST API could help us in this situation. We need something async.

**Comment by saeidakbari-ir** [comment]
It would be very good if we have a Slack channel so we can communicate easier on such topics and then inform it on Github.

**Comment by DrmagicE** [comment]
@saeidakbari-ir   https://join.slack.com/t/gmqtt/shared_invite/zt-keysgtfa-8O82TQjyEXUq1ozZ2nzmnw
