### ISSUE TITLE
How to accept the message sent by the client

### ISSUE THREAD

**Issue by wangning136876** [DrmagicE/gmqtt#85]
I want it to be a broker, but I don’t know how to receive messages from the client

**Comment by DrmagicE** [comment]
If you mean how can a client receive messages from other clients, then the client needs to subscribe the related topics so that it can receive messages. 

If you mean how to get the message payload and do custom logic in the broker, you can write your plugin and use `OnMsgArrived ` hook in your plugin.

**Comment by wangning136876** [comment]
![image](https://user-images.githubusercontent.com/38982292/113867145-bdefa600-97e0-11eb-9114-d553806d7a42.png)

go run . start -c gmqtt.yml

I added a yml file, but the default startup still uses memory

**Comment by DrmagicE** [comment]
Can you show me your main.go?

**Comment by wangning136876** [comment]
does DefaultConfig need me to return to the configuration?
![image](https://user-images.githubusercontent.com/38982292/113868677-871a8f80-97e2-11eb-8b68-2e966c206626.png)

**Comment by DrmagicE** [comment]
Yes, you can follow the Get Start session to start the broker with a specified configuration.  That would be easier.
